services:
  app:
    image: gcr.io/companies-parser/ratings-parser:0.9
    working_dir: /app
    volumes:
      - .:/app
      - ../utils:/app/utils
    env_file:
      - .env
    ports:
      - "80:80"
    command: python app.py
    build:
      context: .
      dockerfile: Dockerfile