import os

GCP_PROJECT = os.getenv("GCP_PROJECT")
INPUT_BUCKET = os.getenv("INPUT_BUCKET")
RATINGS_BUCKET_URL = os.getenv("RATINGS_BUCKET_URL")
DOWNLOADS_FOLDER = os.getenv("DOWNLOADS_FOLDER")
RATINGS_CSV = os.getenv("RATINGS_CSV")